{
 "title": "Monitoring - Live - All Servers - Job Activity Monitor",
 "tags": [
  "mssql",
  "sqlmonitor",
  "Job Activity Monitor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "SQLMonitor Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Server",
    "query": "declare @sql nvarchar(max);\nset quoted_identifier off;\nset @sql = \"\nselect distinct srvname = sql_instance from dbo.instance_details\nwhere is_available = 1 and is_enabled =1\nunion all\nselect '__All__' as srvname \n\torder by srvname\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql;"
   },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME() as [db_name]" },
   {
    "name": "collection_time_utc",
    "label": "Collection Time UTC",
    "query": "select top 1 collection_time_utc = CollectionTimeUTC\nfrom dbo.sql_agent_jobs_all_servers"
   },
   {
    "name": "job_category",
    "label": "Job Category",
    "query": "declare @_sql nvarchar(max);\ndeclare @_params nvarchar(max);\ndeclare @_sql_instance varchar(125);\ndeclare @_job_category varchar(255);\ndeclare @_job_name varchar(255);\ndeclare @_only_enabled_jobs bit = 1;\ndeclare @_next_clock_hours int;\ndeclare @_prev_clock_hours int;\ndeclare @_execution_duration_minutes int;\ndeclare @_is_blocked bit;\ndeclare @_success_ratio_threshold decimal(12,2);\ndeclare @_job_status varchar(20);\n\nset @_params = N'@_sql_instance varchar(125), @_job_category varchar(255), @_job_name varchar(255), @_only_enabled_jobs bit = 1, @_next_clock_hours int, @_prev_clock_hours int, @_execution_duration_minutes int, @_is_blocked bit, @_success_ratio_threshold decimal(12,2), @_job_status varchar(20)';\n\nset quoted_identifier off;\nset @_sql = \"\nselect '__ALL__'\nunion all\nselect [JobCategory]\nfrom dbo.sql_agent_jobs_all_servers saj\ngroup by [JobCategory]\n\"\nset quoted_identifier off;\n\nexec sp_executesql @_sql, @_params, @_sql_instance, @_job_category, @_job_name, @_only_enabled_jobs, @_next_clock_hours, @_prev_clock_hours, @_execution_duration_minutes, @_is_blocked, @_success_ratio_threshold, @_job_status;\n\n\n"
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": "declare @_sql nvarchar(max);\ndeclare @_params nvarchar(max);\ndeclare @_sql_instance varchar(125);\ndeclare @_job_category varchar(255);\ndeclare @_job_name varchar(255);\ndeclare @_only_enabled_jobs bit = 1;\ndeclare @_next_clock_hours int;\ndeclare @_prev_clock_hours int;\ndeclare @_execution_duration_minutes int;\ndeclare @_is_blocked bit;\ndeclare @_success_ratio_threshold decimal(12,2);\ndeclare @_job_status varchar(20);\n\nset @_params = N'@_sql_instance varchar(125), @_job_category varchar(255), @_job_name varchar(255), @_only_enabled_jobs bit = 1, @_next_clock_hours int, @_prev_clock_hours int, @_execution_duration_minutes int, @_is_blocked bit, @_success_ratio_threshold decimal(12,2), @_job_status varchar(20)';\n\nset quoted_identifier off;\nset @_sql = \"\nselect '__ALL__' as [JobName]\nunion all\nselect [JobName]\nfrom dbo.sql_agent_jobs_all_servers saj\ngroup by [JobName]\n\"\nset quoted_identifier off;\n\nexec sp_executesql @_sql, @_params, @_sql_instance, @_job_category, @_job_name, @_only_enabled_jobs, @_next_clock_hours, @_prev_clock_hours, @_execution_duration_minutes, @_is_blocked, @_success_ratio_threshold, @_job_status;\n\n\n"
   },
   { "name": "enabled", "label": "Enabled", "query": "Yes,No,__ALL__" },
   { "name": "blocked", "label": "Blocked", "query": "__ALL__,Yes,No" },
   {
    "name": "success_pct",
    "label": "% Success (>)",
    "query": "-1,10,20,30,40,50,60,70,80,90,100"
   },
   {
    "name": "failure_pct",
    "label": "% Failure (>)",
    "query": "-1,10,20,30,40,50,60,70,80,90,100"
   },
   { "name": "status", "label": "Status", "query": "__All__,Running,Idle" },
   {
    "name": "last_outcome",
    "label": "Last Outcome",
    "query": "__ALL__,Failed,Succeeded,Canceled"
   },
   {
    "name": "next_interval",
    "label": "In Next (Time)",
    "query": "0m,1m,10m,30m,1h,2h,3h,4h,6h,12h,1d,2d,7d,14d,30d"
   },
   {
    "name": "prev_interval",
    "label": "In Prev (Time)",
    "query": "0m,1m,10m,30m,1h,2h,3h,4h,6h,12h,1d,2d,7d,14d,30d"
   },
   { "name": "page_no", "label": "Page No", "query": "1" },
   { "name": "page_size", "label": "Page Size", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Status - Failed/Successful",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\nselect\tsql_instance, \r\n\t\tcounts_success = sum(case when saj.Last_Run_Outcome = 'Succeeded' then 1 else 0 end),\r\n\t\tcounts_failed = sum(case when saj.Last_Run_Outcome = 'Failed' then 1 else 0 end)\r\nfrom dbo.sql_agent_jobs_all_servers saj\r\nwhere 1=1\r\ngroup by sql_instance\r\norder by counts_failed desc, counts_success desc\r\n\"\r\nset quoted_identifier on;\r\n\r\nexec sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Overall Status - Running",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\nselect\tsql_instance, \r\n\t\tcounts = count(*)\r\nfrom dbo.sql_agent_jobs_all_servers saj\r\nwhere 1=1\r\nand Is_Running = 1\r\ngroup by sql_instance\r\norder by counts desc\r\n\"\r\nset quoted_identifier on;\r\n\r\nexec sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Overall Status - Canceled",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\nselect\tsql_instance, \r\n\t\tcounts = count(*)\r\nfrom dbo.sql_agent_jobs_all_servers saj\r\nwhere 1=1\r\nand Last_Run_Outcome = 'Canceled'\r\ngroup by sql_instance\r\norder by counts desc\r\n\"\r\nset quoted_identifier on;\r\n\r\nexec sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Overall Status - Jobs with 50% Failure Rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\nselect\tsql_instance, \r\n\t\tcounts = count(*)\r\nfrom dbo.sql_agent_jobs_all_servers saj\r\nwhere 1=1\r\nand Success_Pcnt < 50\r\nand Total_Executions > 10\r\ngroup by sql_instance\r\norder by counts desc\r\n\"\r\nset quoted_identifier on;\r\n\r\nexec sp_executesql @sql"
    }
   ]
  },
  {
   "title": "All Servers - Job Activity Monitor - FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Servers - Job Activity Monitor - FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "declare @_sql nvarchar(max);\r\ndeclare @_params nvarchar(max);\r\ndeclare @_sql_instance varchar(125);\r\ndeclare @_job_category varchar(255);\r\ndeclare @_job_name varchar(255);\r\ndeclare @_only_enabled_jobs bit;\r\ndeclare @_execution_duration_minutes int;\r\ndeclare @_is_blocked bit;\r\ndeclare @_success_ratio_threshold decimal(12,2);\r\ndeclare @_failure_ratio_threshold decimal(12,2);\r\ndeclare @_job_status varchar(20);\r\ndeclare @_last_outcome varchar(30);\r\ndeclare @_prev_interval varchar(10);\r\ndeclare @_next_interval varchar(10);\r\ndeclare @_prev_clock_time datetime;\r\ndeclare @_next_clock_time datetime;\r\ndeclare @page_no int;\r\ndeclare @page_size int;\r\n\r\nset @_sql_instance = '${server}';\r\nset @_job_category = '$job_category';\r\nset @_job_name = '$job_name';\r\nset @_only_enabled_jobs = case '$enabled' when 'Yes' then 1 when 'No' then 0 else null end;\r\nset @_is_blocked = case '$blocked' when 'Yes' then 1 when 'No' then 0 else null end;\r\nset @_success_ratio_threshold = $success_pct;\r\nset @_failure_ratio_threshold = $failure_pct;\r\nset @_job_status = '$status';\r\nset @_last_outcome = '$last_outcome';\r\nset @_prev_interval = '$prev_interval';\r\nset @_next_interval = '$next_interval';\r\n\r\nif @_prev_interval <> '0m'\r\n    set @_prev_clock_time = case right(@_prev_interval,1) when 'm' then dateadd(minute,-convert(int,left(@_prev_interval,len(@_prev_interval)-1)),getutcdate())\r\n                                     when 'h' then dateadd(hour,-convert(int,left(@_prev_interval,len(@_prev_interval)-1)),getutcdate())\r\n                                    when 'd' then dateadd(day,-convert(int,left(@_prev_interval,len(@_prev_interval)-1)),getutcdate())\r\n                                    else null\r\n                                    end;\r\n\r\nif @_next_interval <> '0m'\r\n    set @_next_clock_time = case right(@_next_interval,1) when 'm' then dateadd(minute,convert(int,left(@_next_interval,len(@_next_interval)-1)),getutcdate())\r\n                                     when 'h' then dateadd(hour,convert(int,left(@_next_interval,len(@_next_interval)-1)),getutcdate())\r\n                                    when 'd' then dateadd(day,convert(int,left(@_next_interval,len(@_next_interval)-1)),getutcdate())\r\n                                    else null\r\n                                    end;\r\n\r\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\r\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\r\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\r\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\r\n\r\n\r\nset @_params = N'@_sql_instance varchar(125), @_job_category varchar(255), @_job_name varchar(255), @_only_enabled_jobs bit = 1, @_next_clock_time datetime, @_prev_clock_time datetime, @_execution_duration_minutes int, @_is_blocked bit, @_success_ratio_threshold decimal(12,2), @_failure_ratio_threshold decimal(12,2), @_job_status varchar(20), @_last_outcome varchar(30), @page_no int, @page_size int';\r\n\r\nset quoted_identifier off;\r\nset @_sql = \"\r\nselect saj.[sql_instance], [JobName], [JobCategory], [IsDisabled], [Last_RunTime], [Last_Run_Duration_Seconds], [Last_Run_Outcome], [Expected_Max_Duration_Minutes], [Successfull_Execution_ClockTime_Threshold_Minutes], [Last_Successful_ExecutionTime], [Last_Successful_Execution_Hours], [Running_Since], [Running_StepName], [Running_Since_Min], [Session_Id], [Blocking_Session_Id], [Next_RunTime], [Total_Executions], [Total_Success_Count], [Total_Stopped_Count], [Total_Failed_Count], [Success_Pcnt], [Continous_Failures], [<10-Min], [10-Min], [30-Min], [1-Hrs], [2-Hrs], [3-Hrs], [6-Hrs], [9-Hrs], [12-Hrs], [18-Hrs], [24-Hrs], [36-Hrs], [48-Hrs], [Is_Running], [CollectionTimeUTC] = [UpdatedDateUTC]\r\nfrom dbo.sql_agent_jobs_all_servers saj\r\nwhere 1=1\r\n\"+(case when @_sql_instance = '__ALL__' then '--' else '' end)+\"and saj.sql_instance in (select case when id.source_sql_instance is not null then id.source_sql_instance else id.sql_instance end from dbo.instance_details id where id.sql_instance = @_sql_instance or id.source_sql_instance = @_sql_instance)\r\n\"+(case when @_job_category = '__ALL__' then '--' else '' end)+\"and [JobCategory] = @_job_category\r\n\"+(case when @_job_name = '__ALL__' then '--' else '' end)+\"and [JobName] = @_job_name\r\n\"+(case when @_only_enabled_jobs is null then '--' else '' end)+\"and [IsDisabled] = ~@_only_enabled_jobs\r\n\"+(case when @_is_blocked = 1 then '' else '--' end)+\"and [Blocking_Session_Id] is not null\r\n\"+(case when @_is_blocked = 0 then '' else '--' end)+\"and [Blocking_Session_Id] is null\r\n\"+(case when @_success_ratio_threshold = -1 then '--' else '' end)+\"and (case when [Total_Executions] = 0 then 0 else [Total_Success_Count]*100.0/[Total_Executions] end) >= @_success_ratio_threshold\r\n\"+(case when @_failure_ratio_threshold = -1 then '--' else '' end)+\"and (case when [Total_Executions] = 0 then 0 else [Total_Failed_Count]*100.0/[Total_Executions] end) >= @_failure_ratio_threshold\r\n\"+(case when @_job_status = 'Running' then '' else '--' end)+\"and Running_Since is not null\r\n\"+(case when @_job_status = 'Idle' then '' else '--' end)+\"and Running_Since is null\r\n\"+(case when @_last_outcome = '__ALL__' then '--' else '' end)+\"and Last_Run_Outcome = @_last_outcome\r\n\"+(case when @_next_clock_time is null then '--' else '' end)+\"and Next_RunTime <= @_next_clock_time\r\n\"+(case when @_prev_clock_time is null then '--' else '' end)+\"and Last_RunTime >= @_prev_clock_time\r\n\"\r\n\r\nset @_sql += \"\r\norder by sql_instance, JobName\r\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only\r\n\"\r\nset quoted_identifier off;\r\n\r\nexec sp_executesql @_sql, @_params, @_sql_instance, @_job_category, @_job_name, @_only_enabled_jobs, @_next_clock_time, @_prev_clock_time, @_execution_duration_minutes, @_is_blocked, @_success_ratio_threshold, @_failure_ratio_threshold, @_job_status, @_last_outcome, @page_no, @page_size;\r\n"
      }
     ]
    }
   ]
  }
 ]
}